---
title: "R-Basics"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


# Problem 1


```{r}
1+1
5/7
```

# Problem 2

helpful tip - "r eval=FALSE" in "{r}"(will not run code but display it)

```{r}
rich <- 1
rich

```

# Problem 3


```{r}
array1 <- 1
for(i in 2:100){
  array1 <-c(array1, i)
}
array1
```
*returns a set of numbers (all real numbers)

**alternatively**
```{r}
array2 <- seq(1,100)
array2
```
*returns a set of integers

# Problem 4

```{r}
array3 <- sum(seq(1,100))
array3
```

# Problem 5 

```{r}
mySum<- function (x,y) {
  sumVector <- sum(seq(x,y))
  return(sumVector)
}

mySum(1,5)
```

#Problem 6

```{r}
array4 <- seq(1,100,2)
array4
```

**alternatively**

```{r}
array5 <- c()

for(i in 1:100){
  if(i%%2 > 0){
    array5<-c(array5,i)
  }
}
array5

```

#Problem 7

```{r}
i <- 3
array6 <- c(2)
repeat{
  array6 <- c(array6, i)
  i <- i + 2
    if(i >= 100){
      break;
    }
}
array6
 
```
